package gui;

import ModelsDAO.EstadisticasDAO;
import ModelsDAO.VolcanDAO;
import ModelsDTO.EstadisticasVolcan;
import ModelsDTO.Volcan;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author seth
 */
public class frmEstadisticasVolcan extends javax.swing.JFrame {

    private EstadisticasDAO estadisticasDAO = new EstadisticasDAO();
    private VolcanDAO volcanDAO = new VolcanDAO();
    private int volcanSeleccionadoId;
    
    /** Creates new form frmEstadisticasVolcan */
    public frmEstadisticasVolcan() {
        initComponents();
        this.setTitle("Estadísticas de Volcanes");
        this.setLocationRelativeTo(null);
        cargarVolcanes();
        inicializarLabels();
    }
    
    private void cargarVolcanes() {
        try {
            List<Volcan> volcanes = volcanDAO.obtenerVolcanesConFiltro(null, null, null);
            DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
            
            for (Volcan volcan : volcanes) {
                modelo.addElement(volcan.getID() + " - " + volcan.getNombre());
            }
            
            cmbVolcanes.setModel(modelo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar los volcanes: " + ex.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void inicializarLabels() {
        lblNombreVolcan.setText("-");
        lblEstadoVolcan.setText("-");
        lblTotalSismos.setText("0");
        lblPromedioMagnitud.setText("0.0");
        lblTotalErupciones.setText("0");
        lblSensoresOperativos.setText("0");
        lblSensoresFalla.setText("0");
        lblTotalSensores.setText("0");
    }
    
    private void actualizarEstadisticas() {
        if (volcanSeleccionadoId <= 0) {
            return;
        }
        
        try {
            EstadisticasVolcan estadisticas = estadisticasDAO.obtenerEstadisticasVolcan(volcanSeleccionadoId);
            
            if (estadisticas != null) {
                lblNombreVolcan.setText(estadisticas.getNombreVolcan());
                lblEstadoVolcan.setText(estadisticas.getEstadoVolcan());
                
                // Aplicar colores según el estado
                switch (estadisticas.getEstadoVolcan()) {
                    case "Activo":
                        lblEstadoVolcan.setForeground(new java.awt.Color(0, 128, 0)); // Verde
                        break;
                    case "Inactivo":
                        lblEstadoVolcan.setForeground(new java.awt.Color(128, 128, 128)); // Gris
                        break;
                    case "Alerta":
                        lblEstadoVolcan.setForeground(new java.awt.Color(255, 165, 0)); // Naranja
                        break;
                    case "Erupción":
                        lblEstadoVolcan.setForeground(new java.awt.Color(255, 0, 0)); // Rojo
                        break;
                    default:
                        lblEstadoVolcan.setForeground(new java.awt.Color(0, 0, 0)); // Negro (por defecto)
                }
                
                lblTotalSismos.setText(String.valueOf(estadisticas.getTotalSismos()));
                lblPromedioMagnitud.setText(estadisticas.getPromedioMagnitud().toString());
                lblTotalErupciones.setText(String.valueOf(estadisticas.getTotalErupciones()));
                lblSensoresOperativos.setText(String.valueOf(estadisticas.getSensoresOperativos()));
                lblSensoresFalla.setText(String.valueOf(estadisticas.getSensoresFalla()));
                lblTotalSensores.setText(String.valueOf(estadisticas.getTotalSensores()));
                
                // Actualizar barra de progreso
                int porcentajeOperativos = 0;
                if (estadisticas.getTotalSensores() > 0) {
                    porcentajeOperativos = (int) ((double) estadisticas.getSensoresOperativos() / estadisticas.getTotalSensores() * 100);
                }
                prgSensores.setValue(porcentajeOperativos);
            } else {
                inicializarLabels();
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al obtener estadísticas: " + ex.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbVolcanes = new javax.swing.JComboBox<>();
        btnRefrescar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblNombreVolcan = new javax.swing.JLabel();
        lblEstadoVolcan = new javax.swing.JLabel();
        lblTotalSismos = new javax.swing.JLabel();
        lblPromedioMagnitud = new javax.swing.JLabel();
        lblTotalErupciones = new javax.swing.JLabel();
        lblSensoresOperativos = new javax.swing.JLabel();
        lblSensoresFalla = new javax.swing.JLabel();
        lblTotalSensores = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        prgSensores = new javax.swing.JProgressBar();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Estadísticas de Volcanes");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Selección de Volcán"));

        jLabel2.setText("Volcán:");

        cmbVolcanes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un volcán" }));
        cmbVolcanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVolcanesActionPerformed(evt);
            }
        });

        btnRefrescar.setText("Refrescar");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(cmbVolcanes, 0, 429, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnRefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbVolcanes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefrescar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Estadísticos"));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nombre del Volcán:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Estado:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Total de Sismos:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Promedio de Magnitud:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Total de Erupciones:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Sensores Operativos:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Sensores en Falla:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Total de Sensores:");

        lblNombreVolcan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreVolcan.setText("-");

        lblEstadoVolcan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEstadoVolcan.setText("-");

        lblTotalSismos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotalSismos.setText("0");

        lblPromedioMagnitud.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPromedioMagnitud.setText("0.0");

        lblTotalErupciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotalErupciones.setText("0");

        lblSensoresOperativos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSensoresOperativos.setText("0");

        lblSensoresFalla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSensoresFalla.setText("0");

        lblTotalSensores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotalSensores.setText("0");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Estado de Sensores:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreVolcan)
                            .addComponent(lblEstadoVolcan)
                            .addComponent(lblTotalSismos)
                            .addComponent(lblPromedioMagnitud)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(prgSensores, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalSensores))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(lblSensoresFalla))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(lblSensoresOperativos))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalErupciones)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(lblNombreVolcan)
                    .addComponent(lblTotalErupciones))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(lblEstadoVolcan)
                    .addComponent(lblSensoresOperativos))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(lblTotalSismos)
                    .addComponent(lblSensoresFalla))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(lblPromedioMagnitud)
                    .addComponent(lblTotalSensores))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prgSensores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void cmbVolcanesActionPerformed(java.awt.event.ActionEvent evt) {                                            
        if (cmbVolcanes.getSelectedIndex() != -1) {
            String seleccionado = cmbVolcanes.getSelectedItem().toString();
            String[] partes = seleccionado.split(" - ");
            volcanSeleccionadoId = Integer.parseInt(partes[0]);
            actualizarEstadisticas();
        }
    }                                           

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        actualizarEstadisticas();
    }                                            

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        this.dispose();
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEstadisticasVolcan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEstadisticasVolcan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEstadisticasVolcan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEstadisticasVolcan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEstadisticasVolcan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JComboBox<String> cmbVolcanes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblEstadoVolcan;
    private javax.swing.JLabel lblNombreVolcan;
    private javax.swing.JLabel lblPromedioMagnitud;
    private javax.swing.JLabel lblSensoresFalla;
    private javax.swing.JLabel lblSensoresOperativos;
    private javax.swing.JLabel lblTotalErupciones;
    private javax.swing.JLabel lblTotalSensores;
    private javax.swing.JLabel lblTotalSismos;
    private javax.swing.JProgressBar prgSensores;
    // End of variables declaration                   
}